const actionMovies = [
  {
    title: 'John Wick',
    id: 19,
    image: 'https://media.themoviedb.org/t/p/w300_and_h450_bestv2/uzHPb0rITwa44KkhX5Z27cXwmL1.jpg',
    releaseDate: '2014-10-24',
    rating: '7.4/10',
    description: 'An ex-hitman comes out of retirement to track down the gangsters that took everything from him.',
    genre: 'Action, Crime, Thriller',
    trailerUrl: 'https://www.youtube.com/watch?v=2AUmvWm5ZD0',
  },
  {
    title: 'Mad Max: Fury Road',
    id: 20,
    image: 'https://media.themoviedb.org/t/p/w300_and_h450_bestv2/hA2ple9q4qnwxp3hKVNhroipsir.jpg',
    releaseDate: '2015-05-15',
    rating: '8.1/10',
    description: 'In a post-apocalyptic wasteland, Max teams up with Furiosa to escape a tyrannical warlord and his army.',
    genre: 'Action, Adventure, Sci-Fi',
    trailerUrl: 'https://www.youtube.com/watch?v=hEJnMQG9ev8',
  },
  {
    title: 'The Dark Knight',
    id: 21,
    image: 'https://media.themoviedb.org/t/p/w300_and_h450_bestv2/kkjTbwV1Xnj8wBL52PjOcXzTbnb.jpg',
    releaseDate: '2008-07-18',
    rating: '9.0/10',
    description: 'Batman faces the Joker, a criminal mastermind who seeks to create chaos in Gotham City.',
    genre: 'Action, Crime, Drama',
    trailerUrl: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
  },
  {
    title: 'Die Hard',
    id: 22,
    image: 'https://media.themoviedb.org/t/p/w300_and_h450_bestv2/yFihWxQcmqcaBR31QM6Y8gT6aYV.jpg',
    releaseDate: '1988-07-15',
    rating: '8.2/10',
    description: 'A New York cop tries to save a building full of hostages from a group of terrorists.',
    genre: 'Action, Thriller',
    trailerUrl: 'https://www.youtube.com/watch?v=2TQmpV5V8xg',
  },
  {
    title: 'The Avengers',
    id: 23,
    image: 'https://media.themoviedb.org/t/p/w300_and_h450_bestv2/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
    releaseDate: '2012-05-04',
    rating: '8.0/10',
    description: 'Earth’s mightiest heroes must come together to stop Loki from subjugating the planet.',
    genre: 'Action, Adventure, Sci-Fi',
    trailerUrl: 'https://www.youtube.com/watch?v=eOrNdBpGMv8',
  },
  {
    title: 'The Bourne Identity',
    id: 24,
    image: 'https://media.themoviedb.org/t/p/w300_and_h450_bestv2/aP8swke3gmowbkfZ6lmNidu0y9p.jpg',
    releaseDate: '2002-06-14',
    rating: '7.9/10',
    description: 'A man suffering from amnesia must figure out who he is and why assassins are trying to kill him.',
    genre: 'Action, Mystery, Thriller',
    trailerUrl: 'https://www.youtube.com/watch?v=cL0Zdcg54p4',
  },
  {
    title: 'Gladiator',
    id: 25,
    image: 'https://media.themoviedb.org/t/p/w300_and_h450_bestv2/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
    releaseDate: '2000-05-05',
    rating: '8.5/10',
    description: 'A betrayed Roman general seeks revenge against the corrupt emperor who murdered his family.',
    genre: 'Action, Adventure, Drama',
    trailerUrl: 'https://www.youtube.com/watch?v=owK1qxDselE',
  },
  {
    title: 'Terminator 2: Judgment Day',
    id: 26,
    image: 'https://media.themoviedb.org/t/p/w300_and_h450_bestv2/k1OuVCYxN8Nt6OE9VbzHXzfJsTy.jpg',
    releaseDate: '1991-07-03',
    rating: '8.5/10',
    description: 'A cyborg is sent from the future to protect a young boy who will grow up to lead humanity in a war against machines.',
    genre: 'Action, Sci-Fi, Thriller',
    trailerUrl: 'https://www.youtube.com/watch?v=BtLQ-l1dJo4',
  },
  {
    title: 'Mission: Impossible – Fallout',
    id: 27,
    image: 'https://media.themoviedb.org/t/p/w300_and_h450_bestv2/dkgCQrG8ESMFDyxZ6VnJi5fBEov.jpg',
    releaseDate: '2018-07-27',
    rating: '7.7/10',
    description: 'Ethan Hunt and his IMF team are tasked with recovering stolen plutonium, but they are soon caught up in a larger conspiracy.',
    genre: 'Action, Adventure, Thriller',
    trailerUrl: 'https://www.youtube.com/watch?v=wb49-oV0F78',
  },
  {
    title: 'The Matrix',
    id: 28,
    image: 'https://media.themoviedb.org/t/p/w300_and_h450_bestv2/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg',
    releaseDate: '1999-03-31',
    rating: '8.7/10',
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    genre: 'Action, Sci-Fi',
    trailerUrl: 'https://www.youtube.com/watch?v=m8e-FF8MsqU',
  },
];

export default actionMovies;
